<?php

include_once('eduglu_chatroom.features.inc');

/**
 * Implementation of hook_menu().
 */
function eduglu_chatroom_menu() {
  $items = array();
  $items['chatroom'] = array(
    'title' => 'Chatroom',
    'page callback' => 'eduglu_chatroom_load',
    'page arguments' => array(),
    'access callback' => 'spaces_access_feature',
    'access arguments' => array('view', 'eduglu_chatroom'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'features',
  );
  return $items;
}

function eduglu_chatroom_load() {
  global $user;

  drupal_add_css(drupal_get_path('module', 'eduglu_chatroom') . '/brunch/build/web/css/main.css', 'module');
  drupal_add_js(drupal_get_path('module', 'eduglu_chatroom') . '/brunch/build/web/js/app.js', 'module');
  drupal_add_js("require('main')", 'inline');
  $load_socketio = <<<code
<script src="http://localhost:3000/socket.io/socket.io.js"></script>
code;
  drupal_set_html_head($load_socketio);

  # Chatroom settings
  $space = spaces_get_space();
  $results = db_query("SELECT u.uid, u.picture as pic, r.realname as name
    FROM og_uid o
    INNER JOIN realname r
    INNER JOIN users u
    WHERE o.uid = r.uid
    AND o.uid = u.uid
    AND o.nid = %d", $space->group->nid);

  $users = array();
  while ($row = db_fetch_object($results)) {
    $row->pic = eduglu_core_create_imagecache_url($row->pic,
      '25x25_crop', 'connected-users');
    $row->id = $row->uid;
    $users[] = $row;
  }

  $key = rand(0, getrandmax());
  setcookie('rediskey', $key);
  $settings = array(
    'chatroom' => array(
      'group' => array(
        'name' => $space->group->title,
        'nid' => $space->group->nid,
        'users' => $users,
      ),
    )
  );

  drupal_add_js($settings, 'setting');


  eduglu_chatroom_post('newUser', array(
    'uid' => $user->uid,
    'group' => $space->group->nid,
    'key' => $key,
  ));

  return "connecting...";
}

/*
 * Function for posting info to node.js server.
 */
function eduglu_chatroom_post($method, $data) {
  // Set some paramenters for sending request.
  $request_url = 'http://localhost:3000/drupal';
  $request_headers = array('Content-Type' => 'application/json');
  $request_method = 'POST';
  $request_retry = 3;
  $data = array(
    'method' => $method,
    'data' => $data,
  );
  $json_data = drupal_to_js($data);

  // Send the request.
  $result = drupal_http_request($request_url, $request_headers, $request_method, $json_data, $request_retry);
  /* print_r($result);*/
}
